# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0145fcab9f867425b5a27081f4c185348874c874d9cc90f2f3f7cbeda03b89a62b06c8690c23393691c1829c4d5e8e634b5a61c965e365a5f5ebda6d4305d07

test:
  secret_key_base: cf7d7d5c7f6a33a4e06b15393d262a5a40cb6f1dc781ce489169b0ceb943441ff1c52e63a0ca501d6fb99d0563113645be302b192a4656ec9d502d4e45565f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
